@startuml particles_database
skinparam {
    Nodesep 100
    Ranksep 100
    Linetype ortho
}

skinparam entity {
    BackgroundColor LightBlue
    FontSize 14
    ArrowThickness 1
}

entity "Fermions" as fermions {
    +id: int [PK]
    --
    +name: text
    +type: enum ('quark', 'lepton')
    +symbol: text
    +spin: double precision
    +mass_display: Text
    +mass_value: double precision
    +mass_uncertainty: double precision
    +electric_charge: double precision
    +generation: enum ('first', 'second', 'third')
    +baryon_number: double precision
    +color_change: text
    +stability: text
    +life_time_display: text
    +life_time_value: double precision
    +life_time_unit: enum('s', 'y')

}

entity "Bosons" as bosons {
    +id: int [PK]
    --
    +name: text
    +symbol: text
    +spin: double precision
    +mass_display: Text
    +mass_value: double precision
    +mass_uncertainty: double precision
    +electric_charge: double precision
    +color_change: text
    +stability: text
    +life_time_display: text
    +life_time_value: double precision
    +life_time_unit: enum('s', 'y')
    +primary_decay_mode: text
}

entity "Forces" as forces {
    +id: serial [PK]
    --
    +name: text
    +description: text
}

entity decay_modes {
    +id: serial [pk]
    --
    +decay_width: double precision
    +min_branching_ratio: double precision
    +max_branching_ratio: double precision
    +role_in_standard_model: text 
}

entity decay_modes_bosons {
    +boson_id: int [PK, FK] references bosons(id)
    +decay_mode_id: int [PK, FK] references decay_modes(id)
}


entity "Boson_Forces" as boson_forces {
    +boson_id: int [PK,FK] references bosons(id)
    +force_id: int [PK, FK] references forces(id)
}

entity "Boson_Fermion" as boson_fermion_interaction{
    +particle_id: int [PK, FK] references fermions(id)
    +boson_id: int [PK, FK] references bosons(id)
}

entity "Users" as users {
    +id: serial [PK]
    --
    +username: text not null
    +email: text not null
    +password: text unique not null
    +created_on: date
}

entity "Token" as tokens {
    +id: serial [pk]
    --
    +token_hash: text unique
    +issued_at: date
    --
    +user_id: int [FK] references users(id)
}

'relationships'

fermions --{ boson_fermion_interaction
bosons --{ boson_fermion_interaction
bosons ---{ boson_forces
forces --{ boson_forces
users --- tokens
decay_modes --{ decay_modes_bosons
bosons --{ decay_modes_bosons

@enduml


